name: Publish to Zenodo (action v0.13.3)

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload code to Zenodo
        uses: zenodraft/action@0.13.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        with:
          # concept: $CONCEPT_ID
          concept: 194376
          metadata: .zenodo.json
          publish: true
          sandbox: true
          verbose: true
          filenames: "metadatav1.9.yml"
          